# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
        run: |
          pipenv run flake8 .
    - name: Test with pytest
      run: |
        pytest . --cov=test
    - name: Posting Coverage
        env:
          CODECOV_TOKEN: "1a4363b3-d7a7-4220-b444-01f3414d0aa7"
        run: |
          pipenv run codecov
